apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "webChart.fullname" . }}-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.website }}
  gateways:
  - gateway-external-lb.istio-system.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ include "webChart.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    timeout: 300s
    retries:
      attempts: 3
